plugins {
    id 'fabric-loom' version '1.2.7'
    id 'maven-publish'
}

loom {

    runs {
        client {
            runDir "run/client"
            ideConfigGenerated true
        }

        server {
            runDir "run/server"
            ideConfigGenerated true
        }
    }
}

repositories {
    maven {
        url 'https://repo.repsy.io/mvn/lucraft/threetag'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    modApi project(":Core")

    modApi("maven.modrinth:gliders:${project.gliders_modrinth_version}")
    modImplementation("maven.modrinth:playeranimator:${project.player_animator_modrinth_version}")
    include("maven.modrinth:playeranimator:${project.player_animator_modrinth_version}")
    modImplementation("net.threetag:PalladiumCore-fabric:${project.palladium_version}")
    include("net.threetag:PalladiumCore-fabric:${project.palladium_version}")

}

remapJar {
    archiveClassifier.set("compat")
}
