plugins {
    id 'fabric-loom' version '1.2.7'
    id 'maven-publish'
}

loom {

    runs {
        client {
            runDir "run/client"
            ideConfigGenerated true
        }

        server {
            runDir "run/server"
            ideConfigGenerated true
        }
    }
}

repositories {

    // Palladium stuff
    maven {
        url 'https://repo.repsy.io/mvn/lucraft/threetag'
    }

    // Cardinal components
    maven {
        url 'https://maven.ladysnake.org/releases'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()

    modImplementation("net.fabricmc:fabric-loader")
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    api project(path: ":Core", configuration: "namedElements")

    modApi("maven.modrinth:gliders:${project.gliders_modrinth_version}")
    modApi("maven.modrinth:playeranimator:${project.player_animator_modrinth_version}")

    modApi "dev.onyxstudios.cardinal-components-api:cardinal-components-base:${project.cardinal_components_version}"
    include "dev.onyxstudios.cardinal-components-api:cardinal-components-base:${project.cardinal_components_version}"
    modApi "dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${project.cardinal_components_version}"
    include "dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${project.cardinal_components_version}"

    modApi "net.threetag:PalladiumCore-fabric:${project.palladium_version}"
    include "net.threetag:PalladiumCore-fabric:${project.palladium_version}"
}

remapJar {
    archiveClassifier.set("compat")
}

configurations.configureEach {
    resolutionStrategy {
        force("net.fabricmc:fabric-loader:${project.loader_version}")
    }
}