
# Fabric Properties | https://modmuss50.me/fabric.html
minecraft_version=1.20.1
parchment_version=parchment-1.20.1:2023.09.03
loader_version=0.15.7
fabric_version=0.92.1+1.20.1

# Mod Properties
mod_version=1
maven_group=me.cg360.mod.grapplemod.compat
archives_base_name=gliders

# Dependencies
grapplemod_target_range=>=1.99.0
gliders_target_range=>=1.1.5
gliders_modrinth_version=9Qu0MGnH
player_animator_modrinth_version=yDqYTUaf
palladium_version=1.20-2.0.0.0
cardinal_components_version=5.0.2

# Compilation Settings
show_dev_warnings=false

